/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_SessionToken {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_SessionToken(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_SessionToken obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_SessionToken(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public void setUsername(String value) {
        ovpncliJNI.ClientAPI_SessionToken_username_set(swigCPtr, value);
    }
    
    public String getUsername() {
        return ovpncliJNI.ClientAPI_SessionToken_username_get(swigCPtr);
    }
    
    public void setSession_id(String value) {
        ovpncliJNI.ClientAPI_SessionToken_session_id_set(swigCPtr, value);
    }
    
    public String getSession_id() {
        return ovpncliJNI.ClientAPI_SessionToken_session_id_get(swigCPtr);
    }
    
    public ClientAPI_SessionToken() {
        this(ovpncliJNI.new_ClientAPI_SessionToken(), true);
    }
}
