/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_MergeConfig {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_MergeConfig(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_MergeConfig obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_MergeConfig(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public void setStatus(String value) {
        ovpncliJNI.ClientAPI_MergeConfig_status_set(swigCPtr, value);
    }
    
    public String getStatus() {
        return ovpncliJNI.ClientAPI_MergeConfig_status_get(swigCPtr);
    }
    
    public void setErrorText(String value) {
        ovpncliJNI.ClientAPI_MergeConfig_errorText_set(swigCPtr, value);
    }
    
    public String getErrorText() {
        return ovpncliJNI.ClientAPI_MergeConfig_errorText_get(swigCPtr);
    }
    
    public void setBasename(String value) {
        ovpncliJNI.ClientAPI_MergeConfig_basename_set(swigCPtr, value);
    }
    
    public String getBasename() {
        return ovpncliJNI.ClientAPI_MergeConfig_basename_get(swigCPtr);
    }
    
    public void setProfileContent(String value) {
        ovpncliJNI.ClientAPI_MergeConfig_profileContent_set(swigCPtr, value);
    }
    
    public String getProfileContent() {
        return ovpncliJNI.ClientAPI_MergeConfig_profileContent_get(swigCPtr);
    }
    
    public void setRefPathList(SWIGTYPE_p_std__vectorT_std__string_t value) {
        // :( Parsing error. Please contact me.
    }
    
    public SWIGTYPE_p_std__vectorT_std__string_t getRefPathList() {
        long cPtr = ovpncliJNI.ClientAPI_MergeConfig_refPathList_get(swigCPtr);
        new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
        return new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
    }
    
    public ClientAPI_MergeConfig() {
        this(ovpncliJNI.new_ClientAPI_MergeConfig(), true);
    }
}
