/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class ClientAPI_LogInfo {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_LogInfo(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_LogInfo obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_LogInfo(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public ClientAPI_LogInfo(String str) {
        this(ovpncliJNI.new_ClientAPI_LogInfo(str), true);
    }
    
    public void setText(String value) {
        ovpncliJNI.ClientAPI_LogInfo_text_set(swigCPtr, value);
    }
    
    public String getText() {
        return ovpncliJNI.ClientAPI_LogInfo_text_get(swigCPtr);
    }
}
