/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class ClientAPI_ConnectionInfo {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_ConnectionInfo(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_ConnectionInfo obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_ConnectionInfo(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public ClientAPI_ConnectionInfo() {
        this(ovpncliJNI.new_ClientAPI_ConnectionInfo(), true);
    }
    
    public void setDefined(boolean value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_defined_set(swigCPtr, value);
    }
    
    public boolean getDefined() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_defined_get(swigCPtr);
    }
    
    public void setUser(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_user_set(swigCPtr, value);
    }
    
    public String getUser() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_user_get(swigCPtr);
    }
    
    public void setServerHost(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_serverHost_set(swigCPtr, value);
    }
    
    public String getServerHost() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_serverHost_get(swigCPtr);
    }
    
    public void setServerPort(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_serverPort_set(swigCPtr, value);
    }
    
    public String getServerPort() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_serverPort_get(swigCPtr);
    }
    
    public void setServerProto(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_serverProto_set(swigCPtr, value);
    }
    
    public String getServerProto() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_serverProto_get(swigCPtr);
    }
    
    public void setServerIp(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_serverIp_set(swigCPtr, value);
    }
    
    public String getServerIp() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_serverIp_get(swigCPtr);
    }
    
    public void setVpnIp4(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_vpnIp4_set(swigCPtr, value);
    }
    
    public String getVpnIp4() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_vpnIp4_get(swigCPtr);
    }
    
    public void setVpnIp6(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_vpnIp6_set(swigCPtr, value);
    }
    
    public String getVpnIp6() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_vpnIp6_get(swigCPtr);
    }
    
    public void setClientIp(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_clientIp_set(swigCPtr, value);
    }
    
    public String getClientIp() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_clientIp_get(swigCPtr);
    }
    
    public void setTunName(String value) {
        ovpncliJNI.ClientAPI_ConnectionInfo_tunName_set(swigCPtr, value);
    }
    
    public String getTunName() {
        return ovpncliJNI.ClientAPI_ConnectionInfo_tunName_get(swigCPtr);
    }
}
