/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_TunBuilderBase {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_TunBuilderBase(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_TunBuilderBase obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_TunBuilderBase(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public boolean tun_builder_new() {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_new(swigCPtr);
    }
    
    public boolean tun_builder_set_remote_address(String address, boolean ipv6) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_set_remote_address(swigCPtr, address, ipv6);
    }
    
    public boolean tun_builder_add_address(String address, int prefix_length, String gateway, boolean ipv6, boolean net30) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_add_address(swigCPtr, this, address, prefix_length, gateway, ipv6, net30);
    }
    
    public boolean tun_builder_reroute_gw(boolean ipv4, boolean ipv6, long flags) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_reroute_gw(swigCPtr, this, ipv4, ipv6, flags);
    }
    
    public boolean tun_builder_add_route(String address, int prefix_length, boolean ipv6) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_add_route(swigCPtr, this, address, prefix_length, ipv6);
    }
    
    public boolean tun_builder_exclude_route(String address, int prefix_length, boolean ipv6) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_exclude_route(swigCPtr, this, address, prefix_length, ipv6);
    }
    
    public boolean tun_builder_add_dns_server(String address, boolean ipv6) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_add_dns_server(swigCPtr, address, ipv6);
    }
    
    public boolean tun_builder_add_search_domain(String domain) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_add_search_domain(swigCPtr, domain);
    }
    
    public boolean tun_builder_set_mtu(int mtu) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_set_mtu(swigCPtr, mtu);
    }
    
    public boolean tun_builder_set_session_name(String name) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_set_session_name(swigCPtr, name);
    }
    
    public boolean tun_builder_add_proxy_bypass(String bypass_host) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_add_proxy_bypass(swigCPtr, bypass_host);
    }
    
    public boolean tun_builder_set_proxy_auto_config_url(String url) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_set_proxy_auto_config_url(swigCPtr, url);
    }
    
    public boolean tun_builder_set_proxy_http(String host, int port) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_set_proxy_http(swigCPtr, host, port);
    }
    
    public boolean tun_builder_set_proxy_https(String host, int port) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_set_proxy_https(swigCPtr, host, port);
    }
    
    public boolean tun_builder_add_wins_server(String address) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_add_wins_server(swigCPtr, address);
    }
    
    public boolean tun_builder_set_block_ipv6(boolean block_ipv6) {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_set_block_ipv6(swigCPtr, block_ipv6);
    }
    
    public int tun_builder_establish() {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_establish(swigCPtr);
    }
    
    public boolean tun_builder_persist() {
        return ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_persist(swigCPtr);
    }
    
    public void tun_builder_establish_lite() {
        ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_establish_lite(swigCPtr);
    }
    
    public void tun_builder_teardown(boolean disconnect) {
        ovpncliJNI.ClientAPI_TunBuilderBase_tun_builder_teardown(swigCPtr, disconnect);
    }
    
    public ClientAPI_TunBuilderBase() {
        this(ovpncliJNI.new_ClientAPI_TunBuilderBase(), true);
    }
}
