/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_LLVector {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_LLVector(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_LLVector obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_LLVector(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public ClientAPI_LLVector() {
        this(ovpncliJNI.new_ClientAPI_LLVector__SWIG_0(), true);
    }
    
    public ClientAPI_LLVector(long n) {
        this(ovpncliJNI.new_ClientAPI_LLVector__SWIG_1(n), true);
    }
    
    public long size() {
        return ovpncliJNI.ClientAPI_LLVector_size(swigCPtr);
    }
    
    public long capacity() {
        return ovpncliJNI.ClientAPI_LLVector_capacity(swigCPtr);
    }
    
    public void reserve(long n) {
        ovpncliJNI.ClientAPI_LLVector_reserve(swigCPtr, n);
    }
    
    public boolean isEmpty() {
        return ovpncliJNI.ClientAPI_LLVector_isEmpty(swigCPtr);
    }
    
    public void clear() {
        ovpncliJNI.ClientAPI_LLVector_clear(swigCPtr);
    }
    
    public void add(long x) {
        ovpncliJNI.ClientAPI_LLVector_add(swigCPtr, x);
    }
    
    public long get(int i) {
        return ovpncliJNI.ClientAPI_LLVector_get(swigCPtr, i);
    }
    
    public void set(int i, long val) {
        ovpncliJNI.ClientAPI_LLVector_set(swigCPtr, this, i, val);
    }
}
