/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_KeyValue {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_KeyValue(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_KeyValue obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_KeyValue(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public void setKey(String value) {
        ovpncliJNI.ClientAPI_KeyValue_key_set(swigCPtr, value);
    }
    
    public String getKey() {
        return ovpncliJNI.ClientAPI_KeyValue_key_get(swigCPtr);
    }
    
    public void setValue(String value) {
        ovpncliJNI.ClientAPI_KeyValue_value_set(swigCPtr, value);
    }
    
    public String getValue() {
        return ovpncliJNI.ClientAPI_KeyValue_value_get(swigCPtr);
    }
    
    public ClientAPI_KeyValue() {
        this(ovpncliJNI.new_ClientAPI_KeyValue(), true);
    }
}
