/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class ClientAPI_DynamicChallenge {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_DynamicChallenge(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_DynamicChallenge obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_DynamicChallenge(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public ClientAPI_DynamicChallenge() {
        this(ovpncliJNI.new_ClientAPI_DynamicChallenge(), true);
    }
    
    public void setChallenge(String value) {
        ovpncliJNI.ClientAPI_DynamicChallenge_challenge_set(swigCPtr, value);
    }
    
    public String getChallenge() {
        return ovpncliJNI.ClientAPI_DynamicChallenge_challenge_get(swigCPtr);
    }
    
    public void setEcho(boolean value) {
        ovpncliJNI.ClientAPI_DynamicChallenge_echo_set(swigCPtr, value);
    }
    
    public boolean getEcho() {
        return ovpncliJNI.ClientAPI_DynamicChallenge_echo_get(swigCPtr);
    }
    
    public void setResponseRequired(boolean value) {
        ovpncliJNI.ClientAPI_DynamicChallenge_responseRequired_set(swigCPtr, value);
    }
    
    public boolean getResponseRequired() {
        return ovpncliJNI.ClientAPI_DynamicChallenge_responseRequired_get(swigCPtr);
    }
}
