/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_ExternalPKIBase {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_ExternalPKIBase(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_ExternalPKIBase obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_ExternalPKIBase(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public boolean sign(String sig_type, String data, SWIGTYPE_p_std__string sig) {
        return ovpncliJNI.ClientAPI_ExternalPKIBase_sign(swigCPtr, this, sig_type, data, SWIGTYPE_p_std__string.getCPtr(sig));
    }
}
