/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class ClientAPI_TransportStats {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_TransportStats(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_TransportStats obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_TransportStats(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public void setBytesIn(long value) {
        ovpncliJNI.ClientAPI_TransportStats_bytesIn_set(swigCPtr, value);
    }
    
    public long getBytesIn() {
        return ovpncliJNI.ClientAPI_TransportStats_bytesIn_get(swigCPtr);
    }
    
    public void setBytesOut(long value) {
        ovpncliJNI.ClientAPI_TransportStats_bytesOut_set(swigCPtr, value);
    }
    
    public long getBytesOut() {
        return ovpncliJNI.ClientAPI_TransportStats_bytesOut_get(swigCPtr);
    }
    
    public void setPacketsIn(long value) {
        ovpncliJNI.ClientAPI_TransportStats_packetsIn_set(swigCPtr, value);
    }
    
    public long getPacketsIn() {
        return ovpncliJNI.ClientAPI_TransportStats_packetsIn_get(swigCPtr);
    }
    
    public void setPacketsOut(long value) {
        ovpncliJNI.ClientAPI_TransportStats_packetsOut_set(swigCPtr, value);
    }
    
    public long getPacketsOut() {
        return ovpncliJNI.ClientAPI_TransportStats_packetsOut_get(swigCPtr);
    }
    
    public void setLastPacketReceived(int value) {
        ovpncliJNI.ClientAPI_TransportStats_lastPacketReceived_set(swigCPtr, value);
    }
    
    public int getLastPacketReceived() {
        return ovpncliJNI.ClientAPI_TransportStats_lastPacketReceived_get(swigCPtr);
    }
    
    public ClientAPI_TransportStats() {
        this(ovpncliJNI.new_ClientAPI_TransportStats(), true);
    }
}
