/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class ClientAPI_ProvideCreds {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_ProvideCreds(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_ProvideCreds obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_ProvideCreds(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public ClientAPI_ProvideCreds() {
        this(ovpncliJNI.new_ClientAPI_ProvideCreds(), true);
    }
    
    public void setUsername(String value) {
        ovpncliJNI.ClientAPI_ProvideCreds_username_set(swigCPtr, value);
    }
    
    public String getUsername() {
        return ovpncliJNI.ClientAPI_ProvideCreds_username_get(swigCPtr);
    }
    
    public void setPassword(String value) {
        ovpncliJNI.ClientAPI_ProvideCreds_password_set(swigCPtr, value);
    }
    
    public String getPassword() {
        return ovpncliJNI.ClientAPI_ProvideCreds_password_get(swigCPtr);
    }
    
    public void setResponse(String value) {
        ovpncliJNI.ClientAPI_ProvideCreds_response_set(swigCPtr, value);
    }
    
    public String getResponse() {
        return ovpncliJNI.ClientAPI_ProvideCreds_response_get(swigCPtr);
    }
    
    public void setDynamicChallengeCookie(String value) {
        ovpncliJNI.ClientAPI_ProvideCreds_dynamicChallengeCookie_set(swigCPtr, value);
    }
    
    public String getDynamicChallengeCookie() {
        return ovpncliJNI.ClientAPI_ProvideCreds_dynamicChallengeCookie_get(swigCPtr);
    }
    
    public void setReplacePasswordWithSessionID(boolean value) {
        ovpncliJNI.ClientAPI_ProvideCreds_replacePasswordWithSessionID_set(swigCPtr, value);
    }
    
    public boolean getReplacePasswordWithSessionID() {
        return ovpncliJNI.ClientAPI_ProvideCreds_replacePasswordWithSessionID_get(swigCPtr);
    }
    
    public void setCachePassword(boolean value) {
        ovpncliJNI.ClientAPI_ProvideCreds_cachePassword_set(swigCPtr, value);
    }
    
    public boolean getCachePassword() {
        return ovpncliJNI.ClientAPI_ProvideCreds_cachePassword_get(swigCPtr);
    }
}
