/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_ExternalPKICertRequest extends ClientAPI_ExternalPKIRequestBase {
    private long swigCPtr;
    
    protected ClientAPI_ExternalPKICertRequest(long cPtr, boolean cMemoryOwn) {
        // :( Parsing error. Please contact me.
    }
    
    protected static long getCPtr(ClientAPI_ExternalPKICertRequest obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_ExternalPKICertRequest(swigCPtr);
            }
            swigCPtr = 0x0;
        }
        super.delete();
    }
    
    public void setCert(String value) {
        ovpncliJNI.ClientAPI_ExternalPKICertRequest_cert_set(swigCPtr, value);
    }
    
    public String getCert() {
        return ovpncliJNI.ClientAPI_ExternalPKICertRequest_cert_get(swigCPtr);
    }
    
    public void setSupportingChain(String value) {
        ovpncliJNI.ClientAPI_ExternalPKICertRequest_supportingChain_set(swigCPtr, value);
    }
    
    public String getSupportingChain() {
        return ovpncliJNI.ClientAPI_ExternalPKICertRequest_supportingChain_get(swigCPtr);
    }
    
    public ClientAPI_ExternalPKICertRequest() {
        this(ovpncliJNI.new_ClientAPI_ExternalPKICertRequest(), true);
    }
}
