/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class ClientAPI_Config {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_Config(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_Config obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_Config(swigCPtr);
            }
            swigCPtr = 0;
        }
    }
    
    public ClientAPI_Config() {
        this(ovpncliJNI.new_ClientAPI_Config(), true);
    }
    
    public void setContent(String value) {
        ovpncliJNI.ClientAPI_Config_content_set(swigCPtr, value);
    }
    
    public String getContent() {
        return ovpncliJNI.ClientAPI_Config_content_get(swigCPtr);
    }
    
    public void setContentList(SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t value) {
        // :( Parsing error. Please contact me.
    }
    
    public SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t getContentList() {
        long cPtr = ovpncliJNI.ClientAPI_Config_contentList_get(swigCPtr);
        new SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t(cPtr, false);
        return new SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t(cPtr, false);
    }
    
    public void setGuiVersion(String value) {
        ovpncliJNI.ClientAPI_Config_guiVersion_set(swigCPtr, value);
    }
    
    public String getGuiVersion() {
        return ovpncliJNI.ClientAPI_Config_guiVersion_get(swigCPtr);
    }
    
    public void setServerOverride(String value) {
        ovpncliJNI.ClientAPI_Config_serverOverride_set(swigCPtr, value);
    }
    
    public String getServerOverride() {
        return ovpncliJNI.ClientAPI_Config_serverOverride_get(swigCPtr);
    }
    
    public void setProtoOverride(String value) {
        ovpncliJNI.ClientAPI_Config_protoOverride_set(swigCPtr, value);
    }
    
    public String getProtoOverride() {
        return ovpncliJNI.ClientAPI_Config_protoOverride_get(swigCPtr);
    }
    
    public void setConnTimeout(int value) {
        ovpncliJNI.ClientAPI_Config_connTimeout_set(swigCPtr, value);
    }
    
    public int getConnTimeout() {
        return ovpncliJNI.ClientAPI_Config_connTimeout_get(swigCPtr);
    }
    
    public void setTunPersist(boolean value) {
        ovpncliJNI.ClientAPI_Config_tunPersist_set(swigCPtr, value);
    }
    
    public boolean getTunPersist() {
        return ovpncliJNI.ClientAPI_Config_tunPersist_get(swigCPtr);
    }
    
    public void setGoogleDnsFallback(boolean value) {
        ovpncliJNI.ClientAPI_Config_googleDnsFallback_set(swigCPtr, value);
    }
    
    public boolean getGoogleDnsFallback() {
        return ovpncliJNI.ClientAPI_Config_googleDnsFallback_get(swigCPtr);
    }
    
    public void setExternalPkiAlias(String value) {
        ovpncliJNI.ClientAPI_Config_externalPkiAlias_set(swigCPtr, value);
    }
    
    public String getExternalPkiAlias() {
        return ovpncliJNI.ClientAPI_Config_externalPkiAlias_get(swigCPtr);
    }
    
    public void setDisableClientCert(boolean value) {
        ovpncliJNI.ClientAPI_Config_disableClientCert_set(swigCPtr, value);
    }
    
    public boolean getDisableClientCert() {
        return ovpncliJNI.ClientAPI_Config_disableClientCert_get(swigCPtr);
    }
    
    public void setCompressionMode(String value) {
        ovpncliJNI.ClientAPI_Config_compressionMode_set(swigCPtr, value);
    }
    
    public String getCompressionMode() {
        return ovpncliJNI.ClientAPI_Config_compressionMode_get(swigCPtr);
    }
    
    public void setPrivateKeyPassword(String value) {
        ovpncliJNI.ClientAPI_Config_privateKeyPassword_set(swigCPtr, value);
    }
    
    public String getPrivateKeyPassword() {
        return ovpncliJNI.ClientAPI_Config_privateKeyPassword_get(swigCPtr);
    }
    
    public void setDefaultKeyDirection(int value) {
        ovpncliJNI.ClientAPI_Config_defaultKeyDirection_set(swigCPtr, value);
    }
    
    public int getDefaultKeyDirection() {
        return ovpncliJNI.ClientAPI_Config_defaultKeyDirection_get(swigCPtr);
    }
    
    public void setForceAesCbcCiphersuites(boolean value) {
        ovpncliJNI.ClientAPI_Config_forceAesCbcCiphersuites_set(swigCPtr, value);
    }
    
    public boolean getForceAesCbcCiphersuites() {
        return ovpncliJNI.ClientAPI_Config_forceAesCbcCiphersuites_get(swigCPtr);
    }
    
    public void setTlsVersionMinOverride(String value) {
        ovpncliJNI.ClientAPI_Config_tlsVersionMinOverride_set(swigCPtr, value);
    }
    
    public String getTlsVersionMinOverride() {
        return ovpncliJNI.ClientAPI_Config_tlsVersionMinOverride_get(swigCPtr);
    }
    
    public void setProxyHost(String value) {
        ovpncliJNI.ClientAPI_Config_proxyHost_set(swigCPtr, value);
    }
    
    public String getProxyHost() {
        return ovpncliJNI.ClientAPI_Config_proxyHost_get(swigCPtr);
    }
    
    public void setProxyPort(String value) {
        ovpncliJNI.ClientAPI_Config_proxyPort_set(swigCPtr, value);
    }
    
    public String getProxyPort() {
        return ovpncliJNI.ClientAPI_Config_proxyPort_get(swigCPtr);
    }
    
    public void setProxyUsername(String value) {
        ovpncliJNI.ClientAPI_Config_proxyUsername_set(swigCPtr, value);
    }
    
    public String getProxyUsername() {
        return ovpncliJNI.ClientAPI_Config_proxyUsername_get(swigCPtr);
    }
    
    public void setProxyPassword(String value) {
        ovpncliJNI.ClientAPI_Config_proxyPassword_set(swigCPtr, value);
    }
    
    public String getProxyPassword() {
        return ovpncliJNI.ClientAPI_Config_proxyPassword_get(swigCPtr);
    }
    
    public void setProxyAllowCleartextAuth(boolean value) {
        ovpncliJNI.ClientAPI_Config_proxyAllowCleartextAuth_set(swigCPtr, value);
    }
    
    public boolean getProxyAllowCleartextAuth() {
        return ovpncliJNI.ClientAPI_Config_proxyAllowCleartextAuth_get(swigCPtr);
    }
    
    public void setAltProxy(boolean value) {
        ovpncliJNI.ClientAPI_Config_altProxy_set(swigCPtr, value);
    }
    
    public boolean getAltProxy() {
        return ovpncliJNI.ClientAPI_Config_altProxy_get(swigCPtr);
    }
}
