/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_EvalConfig {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_EvalConfig(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_EvalConfig obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_EvalConfig(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public ClientAPI_EvalConfig() {
        this(ovpncliJNI.new_ClientAPI_EvalConfig(), true);
    }
    
    public void setError(boolean value) {
        ovpncliJNI.ClientAPI_EvalConfig_error_set(swigCPtr, value);
    }
    
    public boolean getError() {
        return ovpncliJNI.ClientAPI_EvalConfig_error_get(swigCPtr);
    }
    
    public void setMessage(String value) {
        ovpncliJNI.ClientAPI_EvalConfig_message_set(swigCPtr, value);
    }
    
    public String getMessage() {
        return ovpncliJNI.ClientAPI_EvalConfig_message_get(swigCPtr);
    }
    
    public void setUserlockedUsername(String value) {
        ovpncliJNI.ClientAPI_EvalConfig_userlockedUsername_set(swigCPtr, value);
    }
    
    public String getUserlockedUsername() {
        return ovpncliJNI.ClientAPI_EvalConfig_userlockedUsername_get(swigCPtr);
    }
    
    public void setProfileName(String value) {
        ovpncliJNI.ClientAPI_EvalConfig_profileName_set(swigCPtr, value);
    }
    
    public String getProfileName() {
        return ovpncliJNI.ClientAPI_EvalConfig_profileName_get(swigCPtr);
    }
    
    public void setFriendlyName(String value) {
        ovpncliJNI.ClientAPI_EvalConfig_friendlyName_set(swigCPtr, value);
    }
    
    public String getFriendlyName() {
        return ovpncliJNI.ClientAPI_EvalConfig_friendlyName_get(swigCPtr);
    }
    
    public void setAutologin(boolean value) {
        ovpncliJNI.ClientAPI_EvalConfig_autologin_set(swigCPtr, value);
    }
    
    public boolean getAutologin() {
        return ovpncliJNI.ClientAPI_EvalConfig_autologin_get(swigCPtr);
    }
    
    public void setExternalPki(boolean value) {
        ovpncliJNI.ClientAPI_EvalConfig_externalPki_set(swigCPtr, value);
    }
    
    public boolean getExternalPki() {
        return ovpncliJNI.ClientAPI_EvalConfig_externalPki_get(swigCPtr);
    }
    
    public void setStaticChallenge(String value) {
        ovpncliJNI.ClientAPI_EvalConfig_staticChallenge_set(swigCPtr, value);
    }
    
    public String getStaticChallenge() {
        return ovpncliJNI.ClientAPI_EvalConfig_staticChallenge_get(swigCPtr);
    }
    
    public void setStaticChallengeEcho(boolean value) {
        ovpncliJNI.ClientAPI_EvalConfig_staticChallengeEcho_set(swigCPtr, value);
    }
    
    public boolean getStaticChallengeEcho() {
        return ovpncliJNI.ClientAPI_EvalConfig_staticChallengeEcho_get(swigCPtr);
    }
    
    public void setPrivateKeyPasswordRequired(boolean value) {
        ovpncliJNI.ClientAPI_EvalConfig_privateKeyPasswordRequired_set(swigCPtr, value);
    }
    
    public boolean getPrivateKeyPasswordRequired() {
        return ovpncliJNI.ClientAPI_EvalConfig_privateKeyPasswordRequired_get(swigCPtr);
    }
    
    public void setAllowPasswordSave(boolean value) {
        ovpncliJNI.ClientAPI_EvalConfig_allowPasswordSave_set(swigCPtr, value);
    }
    
    public boolean getAllowPasswordSave() {
        return ovpncliJNI.ClientAPI_EvalConfig_allowPasswordSave_get(swigCPtr);
    }
    
    public void setServerList(ClientAPI_ServerEntryVector value) {
        ovpncliJNI.ClientAPI_EvalConfig_serverList_set(swigCPtr, this, ClientAPI_ServerEntryVector.getCPtr(value), value);
    }
    
    public ClientAPI_ServerEntryVector getServerList() {
        long cPtr = ovpncliJNI.ClientAPI_EvalConfig_serverList_get(swigCPtr);
        new ClientAPI_ServerEntryVector(cPtr, false);
        return new ClientAPI_ServerEntryVector(cPtr, false);
    }
}
