/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_ExternalPKISignRequest extends ClientAPI_ExternalPKIRequestBase {
    private long swigCPtr;
    
    protected ClientAPI_ExternalPKISignRequest(long cPtr, boolean cMemoryOwn) {
        // :( Parsing error. Please contact me.
    }
    
    protected static long getCPtr(ClientAPI_ExternalPKISignRequest obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_ExternalPKISignRequest(swigCPtr);
            }
            swigCPtr = 0x0;
        }
        super.delete();
    }
    
    public void setSigType(String value) {
        ovpncliJNI.ClientAPI_ExternalPKISignRequest_sigType_set(swigCPtr, value);
    }
    
    public String getSigType() {
        return ovpncliJNI.ClientAPI_ExternalPKISignRequest_sigType_get(swigCPtr);
    }
    
    public void setData(String value) {
        ovpncliJNI.ClientAPI_ExternalPKISignRequest_data_set(swigCPtr, value);
    }
    
    public String getData() {
        return ovpncliJNI.ClientAPI_ExternalPKISignRequest_data_get(swigCPtr);
    }
    
    public void setSig(String value) {
        ovpncliJNI.ClientAPI_ExternalPKISignRequest_sig_set(swigCPtr, value);
    }
    
    public String getSig() {
        return ovpncliJNI.ClientAPI_ExternalPKISignRequest_sig_get(swigCPtr);
    }
    
    public ClientAPI_ExternalPKISignRequest() {
        this(ovpncliJNI.new_ClientAPI_ExternalPKISignRequest(), true);
    }
}
