/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class ClientAPI_Event {
    protected boolean swigCMemOwn;
    private long swigCPtr;
    
    protected ClientAPI_Event(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }
    
    protected static long getCPtr(ClientAPI_Event obj) {
        return swigCPtr;
    }
    
    protected void finalize() {
        delete();
    }
    
    public synchronized void delete() {
        if(swigCPtr [cmp] 0x0 != 0) {
            if(swigCMemOwn) {
                swigCMemOwn = false;
                ovpncliJNI.delete_ClientAPI_Event(swigCPtr);
            }
            swigCPtr = 0x0;
        }
    }
    
    public ClientAPI_Event() {
        this(ovpncliJNI.new_ClientAPI_Event(), true);
    }
    
    public void setError(boolean value) {
        ovpncliJNI.ClientAPI_Event_error_set(swigCPtr, value);
    }
    
    public boolean getError() {
        return ovpncliJNI.ClientAPI_Event_error_get(swigCPtr);
    }
    
    public void setName(String value) {
        ovpncliJNI.ClientAPI_Event_name_set(swigCPtr, value);
    }
    
    public String getName() {
        return ovpncliJNI.ClientAPI_Event_name_get(swigCPtr);
    }
    
    public void setInfo(String value) {
        ovpncliJNI.ClientAPI_Event_info_set(swigCPtr, value);
    }
    
    public String getInfo() {
        return ovpncliJNI.ClientAPI_Event_info_get(swigCPtr);
    }
}
