/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class CPUUsage {
    private double end_time;
    private boolean halted;
    private double start_time;
    
    private static native double cpu_usage();
    
    
    public CPUUsage() {
        halted = false;
        start_time = cpu_usage();
        end_time = 0.0;
    }
    
    public double usage() {
        return (double localdouble1 = halted ? end_time : cpu_usage() - start_time);
    }
    
    public void stop() {
        if(!halted) {
            end_time = cpu_usage();
            halted = true;
        }
    }
}
