/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;

import android.os.Bundle;
import java.io.IOException;
import java.util.Locale;
import android.util.Log;
import android.webkit.WebView;
import android.webkit.WebSettings;
import android.view.View;

public class OpenVPNHelp extends OpenVPNClientBase {
    private static final String TAG = "OpenVPNHelp";
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        String language = Locale.getDefault().getLanguage();
        String help_dir = String.format("help/%s", language);
        Log.d("OpenVPNHelp", String.format("Localized help directory: %s", language, help_dir));
        try {
            String help_content = FileUtil.readAsset(this, String.format("%s/index.html", language, help_dir, help_dir));
        } catch(IOException e) {
            int help_content = 0x0;
        }
        if(help_content == null) {
            try {
                help_content = FileUtil.readAsset(this, String.format("%s/index.html", language, help_dir, help_dir, help_dir));
            } catch(IOException e) {
                Log.e("OpenVPNHelp", "error reading help file", e);
                finish();
            }
        }
        WebView webview = new WebView(this);
        webview.getSettings().setBuiltInZoomControls(true);
        setContentView(webview);
        help_content = help_content.replaceAll("\\n+", "%20");
        webview.loadData(help_content, "text/html", "UTF-8");
    }
}
