/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;

import android.view.View;
import android.widget.Button;
import android.widget.ScrollView;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.ArrayDeque;
import java.util.Iterator;
import android.util.Log;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.text.method.MovementMethod;

public class OpenVPNLog extends OpenVPNClientBase implements View.OnClickListener {
    private static final String TAG = "OpenVPNClientLog";
    private Button mPause;
    private Button mResume;
    private ScrollView mScrollView;
    private TextView mTextView;
    private ArrayList<OpenVPNService.LogMsg> pause_buffer;
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(0x7f03000c);
        mTextView = (TextView)findViewById(0x7f0a0085);
        mScrollView = (ScrollView)findViewById(0x7f0a0084);
        mPause = (Button)findViewById(0x7f0a0086);
        mResume = (Button)findViewById(0x7f0a0087);
        mPause.setOnClickListener(this);
        mResume.setOnClickListener(this);
        mTextView.setMovementMethod(ScrollingMovementMethod.getInstance());
        doBindService();
    }
    
    private void set_pause_state(boolean state) {
        if(state) {
            mPause.setVisibility(0x8);
            mResume.setVisibility(0x0);
            pause_buffer = new ArrayList();
            return;
        }
        mPause.setVisibility(0x0);
        mResume.setVisibility(0x8);
        if(pause_buffer != null) {
            for(OpenVPNService.LogMsg lm : pause_buffer) {
                mTextView.append(lm.line);
            }
            scroll_textview_to_bottom();
            pause_buffer = 0x0;
        }
    }
    
    private void scroll_textview_to_bottom() {
        mScrollView.post(new Runnable(this) {
            
            public void run() {
                mScrollView.smoothScrollTo(0x0, mTextView.getBottom());
            }
        });
    }
    
    private void refresh_log_view() {
        ArrayDeque<OpenVPNService.LogMsg> hist = log_history();
        if(hist != null) {
            for(OpenVPNService.LogMsg lm : hist) {
                builder.append(lm.line);
            }
            mTextView.setText(builder.toString());
            scroll_textview_to_bottom();
        }
    }
    
    public void onClick(View v) {
        Log.d("OpenVPNClientLog", "LOG: onClick");
        int viewid = v.getId();
        if(viewid == 0x7f0a0086) {
            Log.d("OpenVPNClientLog", "LOG: onClick PAUSE");
            set_pause_state(true);
            return;
        }
        if(viewid == 0x7f0a0087) {
            Log.d("OpenVPNClientLog", "LOG: onClick RESUME");
            set_pause_state(false);
        }
    }
    
    public void log(OpenVPNService.LogMsg lm) {
        if(pause_buffer == null) {
            mTextView.append(lm.line);
            scroll_textview_to_bottom();
            return;
        }
        pause_buffer.add(lm);
    }
    
    protected void onDestroy() {
        Log.d("OpenVPNClientLog", "LOG: onDestroy");
        stop();
        super.onDestroy();
    }
    
    private void stop() {
        doUnbindService();
    }
    
    protected void post_bind() {
        Log.d("OpenVPNClientLog", "LOG: post_bind");
        refresh_log_view();
        set_pause_state(false);
    }
}
