/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;

import android.preference.PreferenceActivity;
import android.os.Bundle;

public class OpenVPNPrefs extends PreferenceActivity {
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(0x7f040000);
    }
}
