/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;

import android.view.View;
import android.widget.TextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.CheckBox;
import android.os.Handler;
import android.util.Log;
import android.content.Intent;
import android.text.Editable;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.content.SharedPreferences;
import android.view.KeyEvent;
import android.os.SystemClock;

public class OpenVPNProxyCreds extends OpenVPNClientBase implements View.OnClickListener, TextView.OnEditorActionListener {
    private static final String TAG = "OpenVPNProxyCreds";
    Button cancel_button;
    Button ok_button;
    EditText password_edit;
    private PrefUtil prefs;
    TextView prev_creds_not_accepted_textview;
    String profile_name;
    String proxy_name;
    TextView proxy_title_textview;
    CheckBox remember_creds_checkbox;
    private Handler ui_reset_timer_handler;
    private Runnable ui_reset_timer_task;
    EditText username_edit;
    
    public OpenVPNProxyCreds() {
        ui_reset_timer_handler = new Handler();
        ui_reset_timer_task = new Runnable(this) {
            
            public void run() {
                gen_proxy_context_expired_event();
                finish();
            }
        };
    }
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(0x7f03000d);
        prefs = new PrefUtil(PreferenceManager.getDefaultSharedPreferences(this));
        prev_creds_not_accepted_textview = (TextView)findViewById(0x7f0a0089);
        proxy_title_textview = (TextView)findViewById(0x7f0a0088);
        username_edit = (EditText)findViewById(0x7f0a008a);
        password_edit = (EditText)findViewById(0x7f0a008b);
        remember_creds_checkbox = (CheckBox)findViewById(0x7f0a008c);
        ok_button = (Button)findViewById(0x7f0a008d);
        cancel_button = (Button)findViewById(0x7f0a0010);
        ok_button.setOnClickListener(this);
        cancel_button.setOnClickListener(this);
        password_edit.setOnEditorActionListener(this);
        doBindService();
    }
    
    public void onClick(View v) {
        Log.d("OpenVPNProxyCreds", "onClick");
        int viewid = v.getId();
        if(viewid == 0x7f0a008d) {
            if((proxy_name != null) && (profile_name != null)) {
                String prefix = "net.openvpn.openvpn";
                Intent intent = new Intent(this, OpenVPNService.class).setAction("net.openvpn.openvpn.ACTION_SUBMIT_PROXY_CREDS").putExtra(prefix + ".PROFILE", profile_name).putExtra(prefix + ".PROXY_NAME", proxy_name).putExtra(prefix + ".PROXY_USERNAME", username_edit.getText().toString()).putExtra(prefix + ".PROXY_PASSWORD", password_edit.getText().toString()).putExtra(prefix + ".PROXY_REMEMBER_CREDS", remember_creds_checkbox.isChecked());
                startService(intent);
            }
            finish();
            return;
        }
        if(viewid == 0x7f0a0010) {
            finish();
        }
    }
    
    public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
        if((action_enter(actionId, event)) && (v == password_edit)) {
            onClick(ok_button);
            return true;
        }
        return false;
    }
    
    private void cancel_ui_reset() {
        ui_reset_timer_handler.removeCallbacks(ui_reset_timer_task);
    }
    
    private void schedule_ui_reset(long delay) {
        cancel_ui_reset();
        ui_reset_timer_handler.postDelayed(ui_reset_timer_task, delay);
    }
    
    protected void onDestroy() {
        Log.d("OpenVPNProxyCreds", "onDestroy");
        cancel_ui_reset();
        stop();
        super.onDestroy();
    }
    
    private void stop() {
        doUnbindService();
    }
    
    protected void post_bind() {
        Intent intent = getIntent();
        if(intent != null) {
            profile_name = intent.getStringExtra("net.openvpn.openvpn.PROFILE");
            proxy_name = intent.getStringExtra("net.openvpn.openvpn.PROXY_NAME");
            if(proxy_name != null) {
                String proxy_title = String.format(resString(0x7f0600cc), proxy_name);
                proxy_title_textview.setText(proxy_title);
                int n_retries = intent.getIntExtra("net.openvpn.openvpn.N_RETRIES", 0x0);
                if(n_retries > 0) {
                    prev_creds_not_accepted_textview.setVisibility(0x0);
                }
                long expires = intent.getLongExtra("net.openvpn.openvpn.EXPIRES", 0x0);
                if(expires > 0x0) {
                    long remaining_time = expires - SystemClock.elapsedRealtime();
                    if(remaining_time > 0x0) {
                        schedule_ui_reset(remaining_time);
                        return;
                    }
                    finish();
                }
                return;
            }
            finish();
        }
    }
}
