/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


class OpenVPNDebug {
    
    public static String pw_repl(String user, String pw) {
        return pw;
    }
}
