/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;

import android.view.View;
import android.widget.TextView;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.EditText;
import android.util.Log;
import android.text.Editable;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.content.SharedPreferences;
import android.view.KeyEvent;

public class OpenVPNAddShortcut extends OpenVPNClientBase implements View.OnClickListener, TextView.OnEditorActionListener, AdapterView.OnItemSelectedListener {
    private static final String TAG = "OpenVPNAddShortcut";
    private Button cancel_button;
    private Button create_button;
    private PrefUtil prefs;
    private Spinner profile_spin;
    private EditText shortcut_name_edit;
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(0x7f030002);
        prefs = new PrefUtil(PreferenceManager.getDefaultSharedPreferences(this));
        profile_spin = (Spinner)findViewById(0x7f0a0011);
        shortcut_name_edit = (EditText)findViewById(0x7f0a0012);
        create_button = (Button)findViewById(0x7f0a0014);
        cancel_button = (Button)findViewById(0x7f0a0013);
        create_button.setOnClickListener(this);
        cancel_button.setOnClickListener(this);
        profile_spin.setOnItemSelectedListener(this);
        shortcut_name_edit.setOnEditorActionListener(this);
        doBindService();
    }
    
    public void onClick(View v) {
        Log.d("OpenVPNAddShortcut", "onClick");
        int viewid = v.getId();
        if(viewid == 0x7f0a0014) {
            String profile_name = SpinUtil.get_spinner_selected_item(profile_spin);
            String shortcut_name = shortcut_name_edit.getText().toString();
            createConnectShortcut(profile_name, shortcut_name);
        }
        finish();
    }
    
    public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
        if((action_enter(actionId, event)) && (v == shortcut_name_edit)) {
            onClick(create_button);
            return true;
        }
        return false;
    }
    
    protected void onDestroy() {
        Log.d("OpenVPNAddShortcut", "onDestroy");
        stop();
        super.onDestroy();
    }
    
    private void stop() {
        doUnbindService();
    }
    
    protected void post_bind() {
        OpenVPNService.ProfileList proflist = profile_list();
        String[] prof_name_array = 0x0;
        String prof_name = 0x0;
        if((proflist != null) && (proflist.size() > 0)) {
            OpenVPNService.Profile prof = current_profile();
            prof_name = prof.get_name();
            prof_name_array = proflist.profile_names();
        } else {
            profile_spin.setEnabled(false);
            shortcut_name_edit.setEnabled(false);
            create_button.setEnabled(false);
            prof_name = resString(0x7f060097);
            prof_name_array = {
            }
            SpinUtil.show_spinner(this, profile_spin, prof_name_array);
            SpinUtil.set_spinner_selected_item(profile_spin, prof_name);
            set_shortcut_name(prof_name);
        }
        
        public void onItemSelected(AdapterView<?> parent, View v, int position, long id) {
            String profile_name = SpinUtil.get_spinner_selected_item(profile_spin);
            set_shortcut_name(profile_name);
        }
        
        public void onNothingSelected(AdapterView<?> parent) {
        }
        
        private void set_shortcut_name(String name) {
            if(name != null) {
                shortcut_name_edit.setText(name);
                shortcut_name_edit.selectAll();
                shortcut_name_edit.requestFocus();
            }
        }
    }
    