/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;

import android.widget.TextView;
import android.view.View;
import android.os.Bundle;
import java.io.IOException;
import android.content.pm.PackageManager;
import android.content.pm.PackageInfo;
import android.util.Log;

public class OpenVPNAbout extends OpenVPNClientBase {
    private static final String TAG = "OpenVPNAbout";
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(0x7f030000);
        String versionName = "0.0";
        int versionCode = 0x0;
        try {
            PackageInfo pi = getPackageManager().getPackageInfo(getPackageName(), 0x0);
            String versionName = pi.versionName;
            int versionCode = pi.versionCode;
        } catch(Exception e) {
            Log.e("OpenVPNAbout", "cannot obtain version info", e);
        }
        String title = String.format(resString(0x7f060005), versionName, versionCode);
        get_text_view(0x7f0a0000).setText(title);
        get_text_view(0x7f0a0001).setText(get_openvpn_core_platform());
        String expire_string = get_app_expire_string();
        if(expire_string != null) {
            String expire_warn = String.format(resString(0x7f060006), versionName, versionCode, expire_string);
            get_text_view(0x7f0a0003).setText(expire_warn);
        } else {
            findViewById(0x7f0a0002).setVisibility(0x8);
        }
        try {
            String about_txt = FileUtil.readAsset(this, "about.txt");
            get_text_view(0x7f0a0005).setText(about_txt);
            return;
        } catch(IOException e) {
            Log.e("OpenVPNAbout", "Error opening about.txt", e);
        }
    }
    
    private TextView get_text_view(int res_id) {
        return (TextView)findViewById(res_id);
    }
}
