/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;

import android.widget.Spinner;
import android.widget.SpinnerAdapter;
import android.widget.ArrayAdapter;
import android.content.Context;
import java.util.Arrays;

public class SpinUtil {
    
    public static String[] get_spinner_list(Spinner spin) {
        ArrayAdapter<String> aa = (ArrayAdapter)getAdapter();
        if(aa == null) {
            int localconst/41 = 0x0;
        }
        int len = aa.getCount();
        String[] ret = new String[len];
        for(int i = 0x0; i < len; i = i + 0x1) {
            ret[i] = (String)aa.getItem(i);
        }
        return ret;
    }
    
    public static int get_spinner_count(Spinner spin) {
        ArrayAdapter<String> aa = (ArrayAdapter)getAdapter();
        if(aa == null) {
            return 0x0;
        }
        return aa.getCount();
    }
    
    public static String get_spinner_list_item(Spinner spin, int position) {
        ArrayAdapter<String> aa = (ArrayAdapter)getAdapter();
        if(aa == null) {
            return null;
        }
        return (String)aa.getItem(position);
    }
    
    public static String get_spinner_selected_item(Spinner spin) {
        return (String)getSelectedItem();
    }
    
    public static void set_spinner_selected_item(Spinner spin, String selected_item) {
        if(selected_item != null) {
            String sel = get_spinner_selected_item(spin);
            if((sel == null) || (!selected_item.equals(sel))) {
                ArrayAdapter<String> aa = (ArrayAdapter)getAdapter();
                int len = aa.getCount();
                for(int pos = 0x0; pos < len; pos = pos + 0x1) {
                    if(selected_item.equals(aa.getItem(pos))) {
                        setSelection(pos);
                    }
                }
            }
        }
    }
    
    public static void show_spinner(Context context, Spinner spin, String[] content) {
        if(content != null) {
            String[] live_content = get_spinner_list(spin);
            if((live_content == null) || (!Arrays.equals(content, live_content))) {
                ArrayAdapter<String> aa = new ArrayAdapter<String>(context, 0x1090008, content);
                aa.setDropDownViewResource(0x1090009);
                spin.setAdapter(aa);
            }
        }
    }
}
