/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package net.openvpn.openvpn;


public class SWIGTYPE_p_std__string {
    private long swigCPtr;
    
    protected SWIGTYPE_p_std__string(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }
    
    protected SWIGTYPE_p_std__string() {
        swigCPtr = 0x0;
    }
    
    protected static long getCPtr(SWIGTYPE_p_std__string obj) {
        return swigCPtr;
    }
}
