/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package wuxian.com.liu;


public class SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t {
    private long swigCPtr;
    
    protected SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }
    
    protected SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t() {
        swigCPtr = 0x0;
    }
    
    protected static long getCPtr(SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t obj) {
        return swigCPtr;
    }
}
